apiVersion: v1
kind: Secret
metadata:
  name: {{ include "biblioteca-cqrs.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "biblioteca-cqrs.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  # Database Password (base64)
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.newrelic.enabled }}
  # New Relic License Key (base64)
  NEW_RELIC_LICENSE_KEY: {{ .Values.newrelic.licenseKey | b64enc | quote }}
  {{- end }}
